### ISSUE TITLE
Improve Playwright pipeline and tests

### ISSUE THREAD

**Issue by rockstardev** [rockstardev/BTCPayServerPlugins.RockstarDev#84]
- Per @NicolasDorier request switch to running Playwright in docker container
  - This seems to be easily possible: check below what ChatGPT says
- Refactor Test project to be `<Nullable>enable</Nullable>`
- Add test for VendorPay - that navigates all pages in the project

----
ChatGPT on Playwright in docker container:

Use Playwright’s Docker image to run your <code inline="">.NET</code>-based Playwright UI tests (no need to install browsers manually or mess with PowerShell).

Update your GitHub Actions workflow:
```
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.42.0-jammy
      options: --ipc=host

    env:
      CI: true
      BTCPAY_SERVER_URL: http://localhost:14142

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Restore and build
      run: |
        dotnet restore Plugins/BTCPayServer.RockstarDev.Plugins.CashCheckout
        dotnet restore ConfigBuilder
        dotnet restore BTCPayServer.Plugins.Tests
        dotnet build --no-restore

    - name: Run ConfigBuilder
      run: dotnet run --project ConfigBuilder

    - name: Start Docker containers for test
      run: docker compose -f submodules/btcpayserver/BTCPayServer.Tests/docker-compose.yml up -d dev

    - name: Run Playwright UI Tests
      run: dotnet test BTCPayServer.Plugins.Tests --verbosity normal

    - name: Cleanup Docker
      run: docker compose -f submodules/btcpayserver/BTCPayServer.Tests/docker-compose.yml down
```

Benefit | Explanation
-- | --
✅ No browser install logic | The container already has all Playwright browsers installed
✅ No PowerShell or .ps1 headaches | It's Linux-based and everything is pre-wired
✅ Matches real-world Playwright setup | Same base the Playwright team uses
✅ Just works with .NET | The image supports .NET 8 and Playwright C# bindings out of the box

📝 Notes:
- The mcr.microsoft.com/playwright/dotnet:<version> image is officially maintained.
- You can adjust the version (e.g. v1.42.0-jammy) if needed: https://mcr.microsoft.com/en-us/product/playwright/dotnet/tags
- The --ipc=host flag helps Chromium in headless mode with better stability.
